<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.gdd</groupId>
    <artifactId>fedivers</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>jena-utils</module>
        <module>fedivers-core</module>
        <module>fedivers-cli</module>
    </modules>

    <properties>
        <jena.version>5.5.0</jena.version>
        <args4j.version>2.33</args4j.version>
        <maven.compiler.release>26</maven.compiler.release>
        <maven.compiler.source>26</maven.compiler.source>
        <maven.compiler.target>26</maven.compiler.target>
        <maven.surefire.version>3.5.4</maven.surefire.version>
        <maven.compiler.version>3.10.1</maven.compiler.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.version}</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>