package fr.gdd.fedivers.adapters;

import fr.gdd.fedivers.transformers.Quad2Pattern;
import fr.gdd.jena.visitors.ReturningOpVisitor;
import org.apache.jena.graph.*;
import org.apache.jena.sparql.algebra.Op;
import org.apache.jena.sparql.algebra.OpAsQuery;
import org.apache.jena.sparql.algebra.op.*;
import org.apache.jena.sparql.util.ExprUtils;
import org.eclipse.rdf4j.model.util.Values;
import org.eclipse.rdf4j.query.BindingSet;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.query.algebra.*;
import org.eclipse.rdf4j.query.algebra.helpers.AbstractSimpleQueryModelVisitor;
import org.eclipse.rdf4j.query.parser.ParsedQuery;
import org.eclipse.rdf4j.query.parser.QueryParserUtil;

import java.lang.reflect.Field;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Parsing the textual SPARQL query generated by FedUP may sometimes
 * take milliseconds, seconds, or even minutes, depending on the difficulty
 * of the federated query.
 * *
 * To use FedUP with FedX, we need to remove this intermediate representation
 * when too difficult.
 */
public class OpJena2OpFedX implements ReturningOpVisitor<TupleExpr> {

    private static Integer ANON_VARS = 0;

    private static String getAnonName() {
        ANON_VARS += 1;
        return "_anon_" + ANON_VARS;
    }

    @Override
    public TupleExpr visit(OpTriple triple) {
        Var s = getVar(triple.getTriple().getSubject());
        Var p = getVar(triple.getTriple().getPredicate());
        Var o = getVar(triple.getTriple().getObject());
        return new StatementPattern(s, p, o);
    }

    @Override
    public TupleExpr visit(OpBGP bgp) {
        return switch (bgp.getPattern().size()) {
            case 0 -> new EmptySet();
            case 1 -> visit(new OpTriple(bgp.getPattern().get(0)));
            default -> {
                // wrote as nested unions
                Iterator<Triple> ops = bgp.getPattern().iterator();
                TupleExpr left = visit(new OpTriple(ops.next()));
                while (ops.hasNext()) {
                    TupleExpr right = visit(new OpTriple(ops.next()));
                    left = new Join(left, right);
                }
                yield left;
            }
        };
    }

    @Override
    public TupleExpr visit(OpSequence sequence) {
        return switch (sequence.getElements().size()) {
            case 0 -> new EmptySet();
            case 1 -> visit(sequence.getElements().getFirst());
            default -> {
                // wrote as nested unions
                Iterator<Op> ops = sequence.getElements().iterator();
                TupleExpr left = visit(ops.next());
                while (ops.hasNext()) {
                    TupleExpr right = visit(ops.next());
                    left = new Join(left, right);
                }
                yield left;
            }
        };
    }

    @Override
    public TupleExpr visit(OpTable table) {
        final BindingSetAssignment assignment = new BindingSetAssignment();
        final List<BindingSet> bindingSets = new ArrayList<>();
        table.getTable().rows().forEachRemaining(r -> {
//            bindingSets.add(FedXIterator2JenaIterator.createBindingConverse(r.detach()));
//            Warning : removed detach because BackendBindings did not implement it; and removing .detach()
//            did not cause any apparent issue
            bindingSets.add(FedXIterator2JenaIterator.createBindingConverse(r));
        });
        assignment.setBindingSets(bindingSets);
        return assignment;
    }

    @Override
    public TupleExpr visit(OpService req) {
        Var serviceUri = req.getService().isVariable() ?
                Var.of(req.getService().getName()) :
                Var.of(getAnonName(), Values.iri(req.getService().getURI()), true, true);

        Op service = new Quad2Pattern().visit(req.getSubOp());

        return new Service(serviceUri,
                visit(req.getSubOp()),
                OpAsQuery.asQuery(service).toString(),
                Map.of(), // no prefix, already injected in URIs
                "", // baseURI
                req.getSilent());
    }

    @Override
    public TupleExpr visit(OpUnion union) {
        final TupleExpr left = visit(union.getLeft());
        final TupleExpr right = visit(union.getRight());
        return new Union(left, right);
    }

    @Override
    public TupleExpr visit(OpJoin join) {
        final TupleExpr left = visit(join.getLeft());
        final TupleExpr right = visit(join.getRight());
        return new Join(left, right);
    }

    @Override
    public TupleExpr visit(OpLeftJoin lj) {
        ValueExpr expr = null;
        if (Objects.nonNull(lj.getExprs()) && !lj.getExprs().isEmpty()) {
            expr = getValueExpr(String.join("&&",
                    lj.getExprs().getList().stream().map(ExprUtils::fmtSPARQL).toList()));
        }
        return new LeftJoin(visit(lj.getLeft()), visit(lj.getRight()), expr);
    }

    @Override
    public TupleExpr visit(OpConditional cond) {
        return new LeftJoin(visit(cond.getLeft()), visit(cond.getRight()));
    }

    @Override
    public TupleExpr visit(OpDistinct distinct) {
        return new Distinct(visit(distinct.getSubOp()));
    }

    @Override
    public TupleExpr visit(OpProject project) {
        return new Projection(visit(project.getSubOp()),
                new ProjectionElemList(project.getVars().stream().map(v -> new ProjectionElem(v.getVarName())).toList()));
    }

    @Override
    public TupleExpr visit(OpGroup groupBy) {
        if (!groupBy.getAggregators().isEmpty()) { // TODO
            throw new UnsupportedOperationException("Group by aggregators…");
        }
        return new Group(visit(groupBy.getSubOp()),
                groupBy.getGroupVars().getVars().stream().map(Node_Variable::toString).collect(Collectors.toList()));
    }

    @Override
    public TupleExpr visit(OpSlice slice) {
        return new Slice(visit(slice.getSubOp()), slice.getStart(), slice.getLength());
    }

    @Override
    public TupleExpr visit(OpFilter filter) {
        return new Filter(visit(filter.getSubOp()),
                getValueExpr(
                        String.join("&&",
                                filter.getExprs().getList().stream().map(ExprUtils::fmtSPARQL).toList())));
    }

    @Override
    public TupleExpr visit(OpOrder orderBy) {
        return new Order(visit(orderBy.getSubOp()),
                orderBy.getConditions().stream().map(sc->
                    new OrderElem(getValueExpr(ExprUtils.fmtSPARQL(sc.getExpression())))
                ).toList());
    }

    /* ********************************************************************* */

    public static ValueExpr getValueExpr(String ExprAsSPARQL) {
        // TODO This is particularly ugly to get the filter condition in
        // TODO terms of FedX since nothing is set to parse the expression alone
        // TODO and get a `ValueExpr` to create the `Filter` operator…
        ParsedQuery parsedQuery = QueryParserUtil.parseQuery(QueryLanguage.SPARQL,
                "SELECT * WHERE {?s ?p ?o FILTER (" + ExprAsSPARQL + ")}",
                null);

        ValueExpr expr = null;
        try {
            parsedQuery.getTupleExpr().visit(new ValueExprGetterVisitor());
        } catch (ValueExprGetterVisitor.ValueExprException e) {
            expr = e.expr;
            // ((AbstractQueryModelNode) expr).setParentNode(null);
            // TODO very very ugly. But we need to put parent to null otherwise it
            // TODO does not pass an assert in `setParentNode`. Could also disable runtime assertions as
            // TODO it probably should in release mode anyway.
            try {
                Field privateField = AbstractQueryModelNode.class.getDeclaredField("parent");
                privateField.setAccessible(true);
                privateField.set(expr, null);
            } catch (Exception exception) {
                throw new RuntimeException(exception.getMessage());
            }
        }
        return expr;
    }

    /**
     * @param node The node to convert.
     * @return A FedX Var from a Jena Node.
     */
    private static Var getVar(Node node) {
        return switch (node) {
            case Node_Literal lit -> Var.of(getAnonName(), Values.literal(lit.getLiteralLexicalForm()), true, true);
            case Node_URI uri -> Var.of(getAnonName(), Values.iri(uri.getURI()), true, true);
            case Node_Variable var -> Var.of(var.getName());
            default -> throw new UnsupportedOperationException(node.toString());
        };
    }

    /* ************************************************************************************* */

    /**
     * An RDF4J visitor that will probably be useful nowhere else. If this happens, consider moving
     * it to its own file…
     */
    public static class ValueExprGetterVisitor extends AbstractSimpleQueryModelVisitor<RuntimeException> {

        @Override
        public void meet(Filter node)  {
            throw new ValueExprException(node.getCondition());
        }

        /**
         * The exception that goes with the Visitor. It's actually the return value, and
         * not an actual exception. This is probably the proper way to use these RDF4J visitors.
         */
        public static class ValueExprException extends RuntimeException {

            ValueExpr expr;

            public ValueExprException(ValueExpr expr) {
                this.expr = expr;
            }
        }

    }

}
